MODEL:
  TYPE: refine_vgg
  SIZE: '512'
  REFINE: True
  CONV_BODY: efrgnet_vgg.refine_vgg
  NUM_CLASSES: 81
  LOAD_PRETRAINED_WEIGHTS: True
  PRETRAIN_WEIGHTS: './weights/vgg16_reducedfc.pth'


BIG:
  FEATURE_MAPS: [[64, 64], [32, 32], [16, 16], [8, 8]]
  ARM_CHANNELS: [512, 1024, 256, 256]
  ODM_CHANNELS: [256, 256, 256, 256]
  NUM_ANCHORS: [3, 3, 3, 3]
  STEPS: [[8, 8], [16, 16], [32, 32], [64, 64]]
  MIN_SIZES: [30, 64, 128, 256]
  MAX_SIZES: [64, 128, 256, 315]
  ASPECT_RATIOS : [[2, 0.5], [2, 0.5], [2, 0.5], [2, 0.5]]
  CLIP: True
  IMG_WH: [512, 512]
  INPUT_FIXED: True # if you want to input different size, you need to set this False.
  USE_MAX_SIZE: False


DATASETS:
  TRAIN_TYPE: [['2014', 'train'], ['2014', 'valminusminival']]
  VAL_TYPE: [['2014', 'minival']]
#  VAL_TYPE: [['2015', 'test-dev']]
  DATAROOT: '/media/jnie/Storage/ubuntu/DataSets/coco/'
  DATA_TYPE: 'COCO'
  SETS:
    VOC: [['2007', 'trainval'], ['2012', 'trainval']]
    VOC0712PLUS: [['2007', 'trainval'], ['2012', 'trainval'],['2007', 'test']]
    VOC0712: [['2012', '2012_trainval']]
    COCO: [['2014', 'train'], ['2014', 'valminusminival']]
    VOC2007: [['2007', 'test']]
    COCOval: [['2014', 'minival']]
    VOCROOT: 'raid/jing/data/VOCdevkit/'
    COCOROOT: 'data/coco'
  
TEST:
  INPUT_WH: [512, 512]
  CONFIDENCE_THRESH: 0.01
  NMS_OVERLAP: 0.45
  BATCH_SIZE: 1
  




